default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: atask_project_development

test:
  <<: *default
  database: atask_project_test

production:
  <<: *default
  database: atask_project_production
  username: atask_project
  password: <%= ENV['atask_project_DATABASE_PASSWORD'] %>
